### ISSUE TITLE
Library does not work with Feather S2 and Circuit Python 6.x

### ISSUE THREAD

**Issue by jdoscher** [adafruit/Adafruit_CircuitPython_IL0373#13]
Using the guide from Adafruit here:
https://learn.adafruit.com/adafruit-eink-display-breakouts/grayscale-29-overview

The code returns the following error:
`code.py output:
Traceback (most recent call last):
  File "code.py", line 26, in <module>
  File "adafruit_il0373.py", line 184, in __init__
TypeError: extra keyword arguments given`

The offending code is this section, with line 26 the first line here:
`display = adafruit_il0373.IL0373(
    display_bus,
    width=296,
    height=128,
    rotation=270,
    black_bits_inverted=False,
    color_bits_inverted=False,
    grayscale=True,
    refresh_time=1,
)`

The full code is here:
`"""Simple test script for 2.9" 296x128 grayscale display.

Supported products:
  * Adafruit 2.9" Grayscale
    * https://www.adafruit.com/product/4777
  """

import time
import busio
import board
import displayio
import adafruit_il0373

displayio.release_displays()

# This pinout works on a Feather M4 and may need to be altered for other boards.
spi = busio.SPI(board.SCK, board.MOSI)  # Uses SCK and MOSI
epd_cs = board.D9
epd_dc = board.D10

display_bus = displayio.FourWire(
    spi, command=epd_dc, chip_select=epd_cs, baudrate=1000000
)
time.sleep(1)

display = adafruit_il0373.IL0373(
    display_bus,
    width=296,
    height=128,
    rotation=270,
    black_bits_inverted=False,
    color_bits_inverted=False,
    grayscale=True,
    refresh_time=1,
)

g = displayio.Group()

f = open("/display-ruler.bmp", "rb")

pic = displayio.OnDiskBitmap(f)
t = displayio.TileGrid(pic, pixel_shader=displayio.ColorConverter())
g.append(t)

display.show(g)

display.refresh()

print("refreshed")

time.sleep(120)
`

**Comment by tannewt** [comment]
What version of CircuitPython are you using? Please try the absolute latest version. It adds a `grayscale` kwarg to EInkDisplay which this library uses.

**Comment by jdoscher** [comment]
Adafruit CircuitPython 6.0.0-rc.0-4-g3c05a8c68 on 2020-10-17; FeatherS2 with ESP32S2, the latest that I am aware of.

**Comment by FoamyGuy** [comment]
@jdoscher on circuipython.org downloads page under the "absolute newest" section you can click "Browse S3" to get to a listing of all of the built images. Even newer ones than the newest released version. Here is a link to the S3  page for FeatherS2: https://adafruit-circuit-python.s3.amazonaws.com/index.html?prefix=bin/unexpectedmaker_feathers2/en_US/

**Comment by jdoscher** [comment]
Using the same sample code and the latest CP 6.x from today (11/10) and the latest libs from today (11/10) I still get the same error:
`Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Traceback (most recent call last):
  File "code.py", line 26, in <module>
  File "adafruit_il0373.py", line 184, in __init__
TypeError: extra keyword arguments given

Press any key to enter the REPL. Use CTRL-D to reload.`

**Comment by ladyada** [comment]
thats really weird because ive been doing lots of eink stuff with great success


```
import time
import board
from digitalio import DigitalInOut, Direction, Pull
import neopixel
from analogio import AnalogIn
import pulseio
import simpleio
import displayio
import terminalio
from adafruit_display_text import label
import ipaddress
import wifi
import socketpool
import adafruit_requests
import ssl
import espidf
import adafruit_il0373

displayio.release_displays()
display_bus = displayio.FourWire(board.SPI(), command=board.EPD_DC,
                                 chip_select=board.EPD_CS,
                                 reset=board.EPD_RESET, baudrate=1000000)
time.sleep(1)
display = adafruit_il0373.IL0373(
    display_bus,
    width=296,
    height=128,
    rotation=270,
    black_bits_inverted=False,
    color_bits_inverted=False,
    grayscale=True,
    refresh_time=1,
)
"""
f = open("/blinka_strength_tarot_5.bmp", "rb")
pic = displayio.OnDiskBitmap(f)
t = displayio.TileGrid(pic, pixel_shader=displayio.ColorConverter())
g.append(t)

display.refresh()
print("refreshed")
"""

print(dir(board))
print("ESP32 Portal Test")
wifi.radio.connect("adafruit", "ffffffff")
print("ip", wifi.radio.ipv4_address)
ipv4 = ipaddress.ip_address("8.8.4.4")
print("ping", ipv4, ": ", wifi.radio.ping(ipv4))
pool = socketpool.SocketPool(wifi.radio)
requests = adafruit_requests.Session(pool, ssl.create_default_context())

time.sleep(1)
display.refresh()

int_pixels = neopixel.NeoPixel(board.NEOPIXEL, 4, brightness=0.3)
pixel_power = DigitalInOut(board.NEOPIXEL_POWER)
pixel_power.direction = Direction.OUTPUT
pixel_power.value = False
ext_pixels = neopixel.NeoPixel(board.D10, 30, brightness=0.3)

batt_monitor = AnalogIn(board.BATTERY)

spkr_sd = DigitalInOut(board.SPEAKER_ENABLE)
spkr_sd.direction = Direction.OUTPUT
spkr_sd.value = False

i2c = board.I2C()

g = displayio.Group()

bitmap = displayio.Bitmap(display.width, display.height, 1)
palette = displayio.Palette(1)
palette[0] = 0xFFFFFF
# Create a TileGrid using the Bitmap and Palette
tile_grid = displayio.TileGrid(bitmap, pixel_shader=palette, x=0, y=0)
g.append(tile_grid)

text_area = label.Label(terminalio.FONT, text=" "*40,
                        color=0x0, scale=4)
text_area.x = 10
text_area.y = 20
g.append(text_area)
display.show(g)

#jst_in = AnalogIn(board.AD1)
#spkr_pwm = pulseio.PWMOut(board.SPEAKER, frequency=5000, duty_cycle=30000)

buttons = []
button_colors = ((255, 0, 0), (255, 150, 0), (0, 255, 255), (180, 0, 255))
button_tones = (1047, 1318,  1568, 2093)
for p in (board.BUTTON_A, board.BUTTON_B, board.BUTTON_C, board.BUTTON_D):
    switch = DigitalInOut(p)
    switch.direction = Direction.INPUT
    switch.pull = Pull.UP
    buttons.append(switch)

timestamp = time.monotonic()
while True:
    for i, b in enumerate(buttons):
        if not b.value:
            print("Button %c pressed" %chr((ord('A')+i)) )
            pixel_power.value = False
            int_pixels.fill(button_colors[i])
            ext_pixels.fill(button_colors[i])
            spkr_sd.value = True
            simpleio.tone(board.SPEAKER, button_tones[i], 0.25)
            break
    else:
        pixel_power.value = True
        spkr_sd.value = False

    if (time.monotonic() - timestamp) > 5: # once a second...
        print("Battery voltage? ", (batt_monitor.value/65535.0) * 2.6 * 2 )
        #print("JST voltage? ", (jst_in.value/55000.0) * 2.6 )
        while not i2c.try_lock():
            pass
        print("I2C addresses found:", [hex(device_address) for device_address in i2c.scan()])
        i2c.unlock()
        try:
            response = requests.get("https://api.coindesk.com/v1/bpi/currentprice.json")
            print(response.status_code)
            if response.status_code==200:
                coinprice = response.json()['bpi']['USD']['rate_float']
                text_area.text = "Bitcoin:\n$%d" % coinprice
                print(text_area.text)
                display.refresh()
        except RuntimeError as e:
            pass
        timestamp = time.monotonic()


    #spkr_pwm.duty_cycle = 30000
    time.sleep(0.01)
```

**Comment by jdoscher** [comment]
I think this is something with the Feather S2 build.  I don't have any other boards to test on.

**Comment by makermelissa** [comment]
I tested this with the FeatherS2 and GrayScale FeatherWing and got the same result:
```
Traceback (most recent call last):
  File "code.py", line 26, in <module>
  File "/lib/adafruit_il0373.py", line 184, in __init__
TypeError: extra keyword arguments given
```
The same code runs great on the MagTag.

**Comment by tannewt** [comment]
I'm going to move this to circuitpython because it appears to be a weird, board-specific issue.
